EMS-EventManagementSystem/Models/Place.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EMS_EventManagementSystem.Models
{
    public class Place
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        public DateTime CreatedAt { get; set; }

        public Area_Town Area_Town { get; set; }
        [Required]
        [Display(Name = "Area")]
        public int Area_TownId { get; set; }

        public Placetype Placetype { get; set; }
        [Required]
        [Display(Name = "Placetype")]
        public int PlacetypeId { get; set; }
    }
}

EMS-EventManagementSystem/Models/Placetype.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EMS_EventManagementSystem.Models
{
    public class Placetype
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Please enter correct name")]
        [Display(Name = "Place Type")]
        public string Name { get; set; }

        public DateTime CreatedAt { get; set; }
    }
}

EMS-EventManagementSystem/ViewModels/PlaceCardListViewModel.cs
using EMS_EventManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EMS_EventManagementSystem.ViewModels
{
    public class PlaceCardListViewModel
    {
        public IEnumerable<Place> Places { get; set; }
        public Placetype Placetype { get; set; }
        
    }
}

EMS-EventManagementSystem/Controllers/PlaceController.cs
using EMS_EventManagementSystem.Data;
using EMS_EventManagementSystem.Models;
using EMS_EventManagementSystem.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EMS_EventManagementSystem.Controllers
{
    public class PlaceController : Controller
    {
        private readonly ApplicationDbContext context;

        public PlaceController(ApplicationDbContext context)
        {
            this.context = context;
        }
        protected override void Dispose(bool disposing)
        {
            this.context.Dispose();
            base.Dispose(disposing);
        }

        public async Task<IActionResult> Index(int id)
        {
            var placeInDb = new PlaceCardListViewModel()
            {
                Places = await context.Places
                .Where(m => m.PlacetypeId == id)
                .ToListAsync(),

                Placetype = await context.Placetypes.SingleOrDefaultAsync(m => m.Id == id)
            };            
            return View("PlaceCardList", placeInDb);
        }

        public async Task<IActionResult> CreatePlace()
        {
            var placeform = new PlaceFormViewModel() 
            {
                Place = new Place(),
                Placetype = await context.Placetypes.ToListAsync()                
            };
            return View("PlaceForm", placeform);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(Place place)
        {
            if (!ModelState.IsValid)
            {
                var placeform = new PlaceFormViewModel()
                {
                    Place = new Place(),
                    Placetype = await context.Placetypes.ToListAsync()
                    
                };
                return View("PlaceForm", placeform);
            }
            else
            {
                place.CreatedAt = DateTime.Now.Date;
                await context.AddAsync(place);
            }
            await context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

EMS-EventManagementSystem/Views/Place/PlaceCardList.cshtml
@model EMS_EventManagementSystem.ViewModels.PlaceCardListViewModel
@{
    ViewData["Title"] = "PlaceCardList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>@Model.Placetype.Name.ToString()</h3>
<hr />

@if (!Model.Places.Any())
{
    <p class="text-lg-center">Sorry there is no place registered yet!</p>
}
else
{
<div class="row" style="margin:auto">
    @foreach (var place in Model.Places)
    {
        @*<div class="card border-success mb-3" style="max-width: 20rem; margin:auto;">
            <div class="card-header"></div>
            <div class="card-body">
                <h4 class="card-title"></h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>*@
        <div class="card border-success mb-3" style="max-width: 20rem; margin:auto;">
            <h3 class="card-header">@Model.Placetype.Name.ToString()</h3>
            <div class="card-body">
                <h5 class="card-title">@place.Name</h5>
                <h6 class="card-subtitle text-muted">Support card subtitle</h6>
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200" aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
                <rect width="100%" height="100%" fill="#868e96"></rect>
                <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text>
            </svg>
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Cras justo odio</li>
                <li class="list-group-item">Dapibus ac facilisis in</li>
                <li class="list-group-item">Vestibulum at eros</li>
            </ul>
            <div class="card-body">
                <a href="#" class="card-link">Card link</a>
                <a href="#" class="card-link">Another link</a>
            </div>
            <div class="card-footer text-muted">
                2 days ago
            </div>
        </div>
    }
</div>
}

EMS-EventManagementSystem/Views/Place/PlaceForm.cshtml
@model EMS_EventManagementSystem.ViewModels.PlaceFormViewModel

@{
    ViewData["Title"] = "PlacetypeForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Add your Place!</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Save" asp-controller="Place">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Place.Id)
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Place.Name" class="control-label"></label>
                <br />
                <input asp-for="Place.Name" class="form-control" />
                <br />
                <span asp-validation-for="Place.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place.PlacetypeId" class="control-label"></label>
                <br />
                @Html.DropDownListFor(model => model.Place.PlacetypeId, new SelectList(Model.Placetype, "Id", "Name"), "Select Genre Type", new { @class = "form-control" })
                <br />
                <span asp-validation-for="Place.PlacetypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place.Area_Town.Name" class="control-label"></label>
                <br />
                <input asp-for="Place.Area_Town.Name" class="form-control" />
                <br />
                <span asp-validation-for="Place.Area_Town.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place.Area_Town.PostalCode" class="control-label"></label>
                <br />
                <input asp-for="Place.Area_Town.PostalCode" class="form-control" />
                <br />
                <span asp-validation-for="Place.Area_Town.PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place.Area_Town.Street" class="control-label"></label>
                <br />
                <input asp-for="Place.Area_Town.Street" class="form-control" />
                <br />
                <span asp-validation-for="Place.Area_Town.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place.Area_Town.City.Name" class="control-label"></label>
                <br />
                <input asp-for="Place.Area_Town.City.Name" class="form-control" />
                <br />
                <span asp-validation-for="Place.Area_Town.City.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place.Area_Town.City.Country.Name" class="control-label"></label>
                <br />
                <input asp-for="Place.Area_Town.City.Country.Name" class="form-control" />
                <br />
                <span asp-validation-for="Place.Area_Town.City.Country.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Back to List</a>
</div>